# Makefile for Beremiz documentation which uses docker container that contains
# the complete environment with all required packages to build docs.
DOCKERIMG = jubnzv1/beremiz-doc-build:latest
CMD       = docker run --rm -v $(PWD)/..:/source -t $(DOCKERIMG)
TARGETS   = doxy html latexpdf

all:
	@echo "Start build in $(DOCKERIMG) for following targets: $(TARGETS)"
	$(CMD) $(TARGETS)
	@echo "Build in docker finished."

.PHONY: all default
